<?php

namespace App\Doctrine;

use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\Filter\SQLFilter;

/**
 * Class TenantFilter
 *
 * This custom SQL filter automatically intercepts all SQL queries generated by Doctrine.
 * If the queried entity has a relationship mapping to a Tenant, it appends an extra WHERE clause
 * mapping specifically to the active tenant ID, completely isolating database requests.
 */
class TenantFilter extends SQLFilter
{
    /**
     * Appends the tenant_id constraint to the generated SQL query.
     * * @param ClassMetadata $targetEntity The metadata of the entity being queried
     * @param string $targetTableAlias The SQL alias allocated for this entity's table
     */
    public function addFilterConstraint(ClassMetadata $targetEntity, string $targetTableAlias): string
    {
        // Check if the entity has an association named 'tenant'
        if (!$targetEntity->hasAssociation('tenant')) {
            return '';
        }

        try {
            // Retrieve the active tenant UUID parameter from the filter parameters
            // This parameter is safely quoted and verified by Doctrine's parameter binder
            $tenantId = $this->getParameter('tenant_id');
        } catch (\InvalidArgumentException $e) {
            // Return empty if the parameter is not yet registered (e.g. before login)
            return '';
        }

        if (empty($tenantId)) {
            return '';
        }

        // Return the SQL string that will be appended in the WHERE clauses
        return sprintf('%s.tenant_id = %s', $targetTableAlias, $tenantId);
    }
}

